--- a/focal/Dockerfile
+++ b/focal/Dockerfile
@@ -218,7 +218,51 @@
 CMD ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]

+# ---- 1Panel extras for armhf (consumed by seed stage via COPY --from) ----
+COPY tmp /tmp/deps
+COPY 1pwaf /usr/local/openresty/1pwaf
+
+RUN DEBIAN_FRONTEND=noninteractive apt-get update \
+    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git cmake \
+    && cd /tmp/deps \
+    && tar xzf openresty-${RESTY_VERSION}.tar.gz \
+    && git clone --recursive https://github.com/google/ngx_brotli.git /tmp/deps/ngx_brotli \
+    && cd /tmp/deps/ngx_brotli \
+    && git checkout master \
+    && git submodule update --init --recursive \
+    && cd deps/brotli && mkdir -p out && cd out \
+    && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr/local .. \
+    && cmake --build . --config Release -j${RESTY_J} \
+    && cmake --build . --target install \
+    && ldconfig \
+    && cd /tmp/deps/openresty-${RESTY_VERSION} \
+    && eval ./configure -j${RESTY_J} ${_RESTY_CONFIG_DEPS} ${RESTY_CONFIG_OPTIONS} ${RESTY_CONFIG_OPTIONS_MORE} ${RESTY_LUAJIT_OPTIONS} ${RESTY_PCRE_OPTIONS} --add-dynamic-module=/tmp/deps/ngx_brotli \
+    && cd build/nginx-*/ \
+    && make modules -j${RESTY_J} \
+    && mkdir -p /usr/local/openresty/modules/ngx_brotli \
+    && cp objs/ngx_http_brotli_*.so /usr/local/openresty/modules/ngx_brotli/ \
+    && cd /tmp && rm -rf /tmp/deps/openresty-${RESTY_VERSION} /tmp/deps/ngx_brotli \
+    && DEBIAN_FRONTEND=noninteractive apt-get remove -y --purge git cmake \
+    && DEBIAN_FRONTEND=noninteractive apt-get autoremove -y
+
+RUN DEBIAN_FRONTEND=noninteractive apt-get update \
+    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git libsqlite3-dev \
+    && mkdir -p /usr/local/openresty/1pwaf/libraries \
+    && cd /tmp/deps && tar xzf libmaxminddb.tar.gz && cd libmaxminddb-* \
+    && ./configure && make -j${RESTY_J} \
+    && cp -L src/.libs/libmaxminddb.so /usr/local/openresty/1pwaf/libraries/ \
+    && cd /tmp/deps && git clone --branch v3.10.0 --depth 1 https://github.com/client9/libinjection.git \
+    && cd libinjection/src && make libinjection.so -j${RESTY_J} \
+    && cp libinjection.so /usr/local/openresty/1pwaf/libraries/ \
+    && /usr/local/openresty/luajit/bin/luarocks install lsqlite3 \
+    && /usr/local/openresty/luajit/bin/luarocks install luafilesystem \
+    && cd /tmp && rm -rf /tmp/deps \
+    && DEBIAN_FRONTEND=noninteractive apt-get remove -y --purge git libsqlite3-dev \
+    && DEBIAN_FRONTEND=noninteractive apt-get autoremove -y
+
 # Use SIGQUIT instead of default SIGTERM to cleanly drain requests
 # See https://github.com/openresty/docker-openresty/blob/master/README.md#tips--pitfalls
 STOPSIGNAL SIGQUIT
