name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "1Panel version"
        required: true
        default: "1.27.1.2-5-1-focal"
        type: choice
        options:
          - "1.27.1.2-5-1-focal"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment variables
        id: version
        run: |
          VERSION="${{ github.event.inputs.VERSION }}"
          OPENRESTY_VERSION=$(echo "$VERSION" | cut -d'-' -f1,2)
          echo "OPENRESTY_VERSION=${OPENRESTY_VERSION}" >> "$GITHUB_ENV"

      - name: Checkout openresty/docker-openresty
        uses: actions/checkout@v7
        with:
          repository: openresty/docker-openresty
          ref: ${{ env.OPENRESTY_VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./focal/Dockerfile
          platforms: linux/arm/v7
          push: true
          build-args: |
            RESTY_VERSION=${{ env.OPENRESTY_VERSION }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/openresty:${{ github.event.inputs.VERSION }}
          cache-from: type=gha,scope=${{ github.event.inputs.VERSION }}
          cache-to: type=gha,scope=${{ github.event.inputs.VERSION }},mode=max