name: CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "1.*/Dockerfile"
  workflow_dispatch:
    inputs:
      VERSION:
        description: "1Panel version e.g. 1.27.1.2-5-1-focal"
        required: true
        default: "1.27.1.2-5-1-focal"
        type: string

jobs:
  build-base:
    runs-on: ubuntu-24.04

    steps:
      - name: Setup environment variables
        run: |
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
          OPENRESTY_VERSION=$(echo "$VERSION" | cut -d'-' -f1,2)
          echo "OPENRESTY_VERSION=${OPENRESTY_VERSION}" >> "$GITHUB_ENV"

      - name: Checkout openresty/docker-openresty
        uses: actions/checkout@v7
        with:
          repository: openresty/docker-openresty
          ref: ${{ env.OPENRESTY_VERSION }}

